apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-service
  namespace: langfuse
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::936389956156:role/metrics-service-s3-access
  labels:
    app: metrics-service
    component: metrics
