apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-service
  namespace: langfuse
  annotations:
    eks.amazonaws.com/role-arn: ${METRICS_SERVICE_IAM_ROLE_ARN}
  labels:
    app: metrics-service
    component: metrics
